### PR TITLE
update MokaManager to internalize the Arc

### LINKED ISSUE #14: `CacheManger` not implemented for `MokaManager`
image

image

```
error[E0277]: the trait bound `MokaManager: http_cache::CacheManager` is not satisfied
   --> src/client.rs:18:15
    |
18  |         Cache(HttpCache {
    |               ^^^^^^^^^ the trait `http_cache::CacheManager` is not implemented for `MokaManager`
```

### PR DESCRIPTION
**Pull request by FreeMasen**
Closes #14

### CODE REVIEW

**Comment by 06chaynes** [comment]
Looks like I’ll need to bump the MSRV to 1.59 but not really sure why it’s an issue suddenly when no updates were made to dependencies. I see crate that is causing the bump [async-global-executor](https://github.com/async-rs/async-global-executor/blob/master/CHANGELOG.md), just not really sure how it got updated.

**Comment by FreeMasen** [comment]
It may be possible to avoid that by more strictly specifying the dependency in the `Cargo.toml`, I can try and take a look this afternoon as to where that failure is happening.

**Comment by FreeMasen** [comment]
Looks like `cacache` is the culprit, it depends on `async-std = "1.10.0"` which cargo resolves to `1.11.0` when I run `cargo tree -i -p async-global-executor`. I am not sure exactly how this can be fixed w/o updating the MSRV, at least for the cacache tests

**Comment by 06chaynes** [comment]
Thanks for checking into that! I'll probably go ahead with bumping the MSRV to 1.59. I would prefer to keep that a bit further behind latest but I'm also don't care to press the matter much. 

I might revisit this in the future, especially how I have the CI setup to test for MSRV changes. Right now I determine it locally and set it manually to test in the logic, so might be good to run cargo msrv as a step? Something to think about.

In the meantime I'll push forward with these changes and try to get a new version published before too long. Thanks again!

**Comment by 06chaynes** [comment]
Just published this as part of version 0.7.0!

**Comment by FreeMasen** [comment]
Thanks!

**Pull request merged**
